#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout: #no controller, just a route defined here for automatic log out by Symfony Security Component
    path: /user/logout
